version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: db_server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: espl@2017
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"

  registry:
    image: registry:2
    container_name: private_registry
    ports:
      - "5000:5000"
